# Generated by Django 3.2.3 on 2021-06-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_contactos_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='apelido',
            field=models.CharField(default='cabaco', max_length=30),
        ),
        migrations.AddField(
            model_name='contacto',
            name='dataNascimento',
            field=models.DateField(default='2000-12-14'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='telefone',
            field=models.IntegerField(default='911524513'),
        ),
    ]
