# Generated by Django 3.2.3 on 2021-06-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210603_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='apelido',
            field=models.CharField(max_length=30),
        ),
    ]
