# Generated by Django 3.2.4 on 2021-06-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_contacto_apelido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
