# Generated by Django 3.2.4 on 2021-06-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_quizz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizz',
            name='nome',
        ),
        migrations.AddField(
            model_name='quizz',
            name='question_CO2',
            field=models.CharField(default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='quizz',
            name='question_acce',
            field=models.CharField(default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='quizz',
            name='question_auto',
            field=models.CharField(default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='quizz',
            name='question_battery',
            field=models.CharField(default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='quizz',
            name='question_bestseller',
            field=models.CharField(default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='quizz',
            name='question_chargers',
            field=models.CharField(default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='quizz',
            name='question_charging',
            field=models.CharField(default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='quizz',
            name='question_eff',
            field=models.CharField(default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='quizz',
            name='question_horsepower',
            field=models.CharField(default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='quizz',
            name='question_maintenance',
            field=models.CharField(default=1, max_length=30),
        ),
    ]
