# Generated by Django 3.2.4 on 2021-06-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20210618_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoQuizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
