# Generated by Django 3.2.4 on 2021-06-25 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_resultadoquizz_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='contacto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.contacto'),
        ),
    ]
